# Generated by Django 6.1 on 2026-09-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('sector', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Delegación',
                'verbose_name_plural': 'Delegaciones',
                'db_table': 'delegaciones',
                'ordering': ['nombre'],
            },
        ),
    ]
